#!/usr/bin/env bash
# Generate frontend/src/data/test-counts.json from the real pytest suites.
#
# The site's whole promise is that every example is tested, so the test counts
# shown on the cards must come from pytest itself, never hand typed. This walks
# each example, asks pytest how many tests it collects, and writes the result
# as JSON the frontend imports at build time. Run it whenever tests change:
#
#   ./scripts/gen-test-counts.sh
#
# CI runs it too and fails if the committed JSON is stale.
set -euo pipefail

cd "$(dirname "$0")/.."

PY="${PY:-.venv/bin/python}"
[ -x "$PY" ] || PY="python3"

OUT="frontend/src/data/test-counts.json"
tmp="$(mktemp)"

echo "{" > "$tmp"
echo '  "_comment": "Generated by scripts/gen-test-counts.sh from pytest --collect-only. Do not edit by hand.",' >> "$tmp"
echo '  "examples": {' >> "$tmp"

first=1
total=0
for d in examples/*/; do
  [ -d "${d}tests" ] || continue
  name="${d%/}"
  n="$("$PY" -m pytest "$d" --collect-only -q 2>/dev/null | grep -cE "::test_" || true)"
  total=$((total + n))
  if [ "$first" -eq 0 ]; then echo "," >> "$tmp"; fi
  first=0
  printf '    "%s": %s' "$name" "$n" >> "$tmp"
done

echo "" >> "$tmp"
echo "  }," >> "$tmp"
printf '  "total": %s\n' "$total" >> "$tmp"
echo "}" >> "$tmp"

mv "$tmp" "$OUT"
echo "wrote $OUT (total $total tests)"
